/* ============================================================
   samples.js — LC.samples
   Five original passages in a dense, UCAT-style register.
   Written for this project; not copied from any source.
   ============================================================ */

window.LC = window.LC || {};

LC.samples = [
  {
    title: "The ocean as a carbon sink",
    text:
      "The world's oceans absorb roughly a quarter of the carbon dioxide that human activity releases each year, a service so quietly performed that its limits are easily overlooked. When carbon dioxide dissolves in seawater it forms carbonic acid, which dissociates into bicarbonate and hydrogen ions; the accumulation of those hydrogen ions lowers the water's pH in a process termed ocean acidification. Although the absolute change in pH appears modest, the scale is logarithmic, so a shift of a few tenths of a unit represents a substantial increase in acidity. This matters because many marine organisms, from corals to certain plankton, build shells and skeletons from calcium carbonate, a mineral that becomes harder to precipitate as acidity rises. A reasonable inference is that sustained acidification threatens not only individual species but the food webs that depend upon them. Yet the ocean's capacity to absorb carbon is not fixed. Warmer water holds less dissolved gas, so as surface temperatures climb, the efficiency of the sink declines, and a greater fraction of emitted carbon remains in the atmosphere. Some researchers caution against treating the ocean as a reliable buffer, since the very warming that emissions drive may erode the mechanism that has so far moderated their effect. The distinction between a sink that grows with emissions and one that saturates is therefore central to any projection. It would be an error to conclude that the ocean will continue indefinitely to spare the atmosphere from the full weight of industrial output. The evidence instead suggests a system under strain, one whose past performance offers limited assurance about its future behaviour. Policymakers who assume that natural sinks will absorb the consequences of delay may find that the margin they relied upon has narrowed precisely when it was needed most."
  },
  {
    title: "Printing and the spread of literacy",
    text:
      "Before the middle of the fifteenth century, books in Europe were copied by hand, a labour so costly that a single volume might represent months of a scribe's work and a price beyond all but the wealthiest institutions. The introduction of movable type altered this economy abruptly. By assembling reusable metal letters into a frame, a printer could produce hundreds of identical copies in the time a scribe once spent on one, and the cost of a book fell accordingly. It is tempting to credit the new technology directly with the rise of mass literacy, but the relationship was less straightforward than such a claim implies. Printing made texts cheaper, yet a population must first have reason and means to read before cheaper texts matter. In regions where commerce, administration, and reformed religion created practical demand for reading, the press found a ready market; elsewhere its impact was muted for generations. The technology, in other words, amplified forces already present rather than conjuring them from nothing. Critics of any purely technological account also note that printing standardised error as readily as it standardised knowledge, fixing mistakes in thousands of copies that scribes might once have silently corrected. What can be said with confidence is that print lowered the barrier between a writer and a distant, anonymous audience, and that this shift gradually reorganised authority over knowledge. Ideas could now outrun the institutions that had previously controlled their circulation, a development that unsettled both church and crown. To attribute social transformation to a single invention is to mistake a catalyst for a cause. The more defensible position is that movable type reshaped the conditions under which ideas competed, and that the consequences depended on the readiness of the societies that adopted it."
  },
  {
    title: "Comparative advantage and trade",
    text:
      "The argument for international trade rests less on which country can produce a good most cheaply than on a subtler idea known as comparative advantage. A nation may be more efficient than its trading partner at producing every good and still benefit from specialisation, provided it concentrates on those goods for which its relative efficiency is greatest. The reasoning turns on opportunity cost: by devoting resources to the activity it forgoes least by pursuing, a country and its partner can together produce more than either could in isolation, and trade then distributes the surplus. This conclusion is frequently misread as a claim that trade benefits everyone within a country, which it does not assert. The model speaks to aggregate output, not to its distribution, and the gains may accrue to some groups while others bear losses as industries contract. A worker displaced by cheaper imports is unlikely to be consoled by the observation that national income has risen. Defenders of open trade often respond that the winners gain enough to compensate the losers, yet whether such compensation actually occurs is a matter of policy rather than of economic law. The theory therefore establishes a possibility, not a guarantee. It would be a misuse of the principle to invoke it as proof that any particular trade agreement leaves a population better off. A more careful reading treats comparative advantage as an explanation of why specialisation can enlarge the total available to be shared, while leaving open the political question of how that total is divided. The persistence of protectionist sentiment, far from refuting the theory, reflects precisely the gap between aggregate gain and individual experience that the model itself, properly understood, does nothing to deny."
  },
  {
    title: "Consequences and the limits of the trolley problem",
    text:
      "Few thought experiments are invoked as often in introductory ethics as the case of the runaway trolley, in which an agent must decide whether to divert a hurtling vehicle so that it kills one person rather than five. The scenario is designed to isolate an intuition: many who would pull a lever to redirect the trolley balk at pushing a bystander to his death to achieve the same numerical result, even though the arithmetic of lives saved is identical. Consequentialist reasoning, which judges actions solely by their outcomes, struggles to explain this asymmetry, for if only the tally of deaths matters then the two cases should be morally equivalent. Critics seize upon the divergence as evidence that our moral sense recognises something beyond consequences, perhaps a distinction between doing harm and merely allowing it, or between using a person as a means and foreseeing his death as a side effect. Defenders of consequentialism reply that intuitions are not data to be deferred to but reactions to be explained, and possibly to be corrected. The dispute exposes a deeper methodological question: whether moral philosophy should systematise our existing judgements or stand ready to overturn them. It would be hasty to treat the discomfort of pushing a man as decisive refutation of outcome-based ethics, since intuitions formed in ordinary circumstances may mislead us in contrived ones. Equally, it would be complacent to dismiss those intuitions merely because they resist tidy formalisation. The enduring value of the trolley problem lies not in any answer it yields but in the pressure it places on each theory to account for cases that the others find awkward. A framework that explains the easy cases while ignoring the hard ones has not so much solved the problem as declined to confront it."
  },
  {
    title: "Antibiotic resistance and the tragedy of the commons",
    text:
      "The effectiveness of antibiotics is a shared resource, and like many shared resources it is vulnerable to overuse by individuals acting in their own immediate interest. Each time an antibiotic is prescribed, a selective pressure is applied to the bacterial population it targets: susceptible organisms die, while any that happen to carry resistance genes survive and multiply. Over many such episodes the proportion of resistant strains rises, and drugs that once reliably cured infections begin to fail. The logic resembles what economists call the tragedy of the commons, in which a benefit accrues privately while the cost is dispersed across the whole community and deferred into the future. A physician who prescribes an antibiotic for a probably viral illness secures a small, certain reassurance for one patient; the resulting contribution to resistance is negligible in isolation and shared by everyone. Because no single decision appears consequential, the incentives that govern individual choices steer the system toward collective harm. It would be mistaken, however, to lay the problem solely at the door of clinical caution, for a substantial share of antibiotic use occurs in agriculture, where the drugs are administered to promote growth and forestall disease in crowded conditions. The remedy is correspondingly diffuse. Appeals to individual restraint, while reasonable, are unlikely to suffice when the structure of incentives rewards exactly the behaviour that erodes the resource. More promising are measures that alter those incentives directly, through regulation of prescribing, surveillance of resistance patterns, and investment in new drugs whose development the market alone has been slow to fund. The case illustrates a general lesson: where the benefit of an action is concentrated and its cost is shared, exhortation is a weak instrument, and durable solutions must reshape the conditions under which the choices are made."
  }
];
